"""exams questions and booklets

Revision ID: 43c95b10c8c4
Revises: 948dd5e979f4
Create Date: 2026-07-31 13:37:23.770889

Every table here is tenant-scoped, so each one needs an RLS policy and a
grant to the application role. Autogenerate produces neither: a table added
without this block is readable across tenants, and nothing about it looks
wrong until one institution reads another's exams.

`test_every_tenant_table_is_protected` fails the build if a future table
forgets, which is the only reliable defence against this being missed again.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "43c95b10c8c4"
down_revision: str | None = "948dd5e979f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NEW_TABLES = ("exams", "questions", "booklets")
APP_ROLE = "marking_app"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exams",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("total_marks", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("anonymous_marking", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_exams_course_id_courses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_exams_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exams")),
    )
    op.create_index(op.f("ix_exams_tenant_id"), "exams", ["tenant_id"], unique=False)
    op.create_table(
        "booklets",
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("qr_payload", sa.Text(), nullable=False),
        sa.Column("layout_version", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exams.id"], name=op.f("fk_booklets_exam_id_exams"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_booklets_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booklets")),
        sa.UniqueConstraint("qr_payload", name=op.f("uq_booklets_qr_payload")),
    )
    op.create_index(op.f("ix_booklets_tenant_id"), "booklets", ["tenant_id"], unique=False)
    op.create_table(
        "questions",
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Text(), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("max_marks", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("answer_type", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("answer_height_mm", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exams.id"], name=op.f("fk_questions_exam_id_exams"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_questions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("exam_id", "number", name=op.f("uq_questions_exam_id")),
    )
    op.create_index(op.f("ix_questions_tenant_id"), "questions", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    _protect_new_tables()


def downgrade() -> None:
    for table in NEW_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_tenant_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_booklets_tenant_id"), table_name="booklets")
    op.drop_table("booklets")
    op.drop_index(op.f("ix_exams_tenant_id"), table_name="exams")
    op.drop_table("exams")
    # ### end Alembic commands ###


def _protect_new_tables() -> None:
    """RLS plus grants for each new tenant-scoped table.

    Same `NULLIF` guard as the initial migration: `current_setting(..., true)`
    is NULL on a fresh connection but an empty string after RESET, and
    `''::uuid` raises instead of matching nothing. Both must become NULL so an
    unset tenant yields no rows rather than an error.
    """
    tenant_expr = "NULLIF(current_setting('app.tenant_id', true), '')::uuid"

    for table in NEW_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = {tenant_expr})
              WITH CHECK (tenant_id = {tenant_expr})
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO {APP_ROLE}")

    op.execute(f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {APP_ROLE}")
