"""student identity map and enrolments

Both tables are tenant-scoped and therefore need RLS and grants, which
autogenerate does not produce. test_schema_invariants fails the build if
this block is ever omitted.

student_identity_map holds the only directly identifying data in the
system, so it is the table where a missing policy would matter most.

Revision ID: f7b402b377f4
Revises: 43c95b10c8c4
Create Date: 2026-07-31 14:04:52.931986

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f7b402b377f4"
down_revision: str | None = "43c95b10c8c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


NEW_TABLES = ("enrolments", "student_identity_map")
APP_ROLE = "marking_app"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrolments",
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("index_number", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exams.id"], name=op.f("fk_enrolments_exam_id_exams"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_enrolments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrolments")),
        sa.UniqueConstraint("exam_id", "index_number", name=op.f("uq_enrolments_exam_id")),
    )
    op.create_index(op.f("ix_enrolments_tenant_id"), "enrolments", ["tenant_id"], unique=False)
    op.create_table(
        "student_identity_map",
        sa.Column("booklet_id", sa.UUID(), nullable=False),
        sa.Column("index_number_enc", sa.LargeBinary(), nullable=False),
        sa.Column("enrolment_id", sa.UUID(), nullable=True),
        sa.Column("confirmed_by", sa.UUID(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ocr_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("ocr_suggestion", sa.Text(), nullable=True),
        sa.Column("revealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revealed_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booklet_id"],
            ["booklets.id"],
            name=op.f("fk_student_identity_map_booklet_id_booklets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
            name=op.f("fk_student_identity_map_confirmed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["enrolment_id"],
            ["enrolments.id"],
            name=op.f("fk_student_identity_map_enrolment_id_enrolments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revealed_by"],
            ["users.id"],
            name=op.f("fk_student_identity_map_revealed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_student_identity_map_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_identity_map")),
        sa.UniqueConstraint("booklet_id", name=op.f("uq_student_identity_map_booklet_id")),
    )
    op.create_index(
        op.f("ix_student_identity_map_tenant_id"),
        "student_identity_map",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    _protect_new_tables()


def downgrade() -> None:
    for table in NEW_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_student_identity_map_tenant_id"), table_name="student_identity_map")
    op.drop_table("student_identity_map")
    op.drop_index(op.f("ix_enrolments_tenant_id"), table_name="enrolments")
    op.drop_table("enrolments")
    # ### end Alembic commands ###


def _protect_new_tables() -> None:
    """RLS and grants. Same NULL-safe tenant expression as every other table."""
    tenant_expr = "NULLIF(current_setting('app.tenant_id', true), '')::uuid"

    for table in NEW_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = {tenant_expr})
              WITH CHECK (tenant_id = {tenant_expr})
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO {APP_ROLE}")
